### ISSUE TITLE
Compatibility with httpx==0.25.0

### ISSUE THREAD

**Issue by JacobHenner** [pythongssapi/httpx-gssapi#33]
httpx==0.25.0 was released on 2023-09-11. 

httpx-gssapi is marked as compatible with `httpx>=0.16,<0.25`, which excludes 0.25.0:

https://github.com/pythongssapi/httpx-gssapi/blob/69d14ba62181b538b24e05f25f403f5d2d9c8860/setup.cfg#L28

**Comment by aiudirog** [comment]
Thanks for the reminder again! I've released [v0.2.1](https://github.com/pythongssapi/httpx-gssapi/releases/tag/v0.2.1) to take care of this. I'll try and stay on top of the next release, which will hopefully be the last before 1.0 where I can loosen the requirements.

**Comment by JacobHenner** [comment]
Thank you!
